service: sls-offline

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    webpack:
        webpackConfig: ./webpack.serverless.js
        includeModules: true
    serverless-offline:
      noPrependStageInUrl: true

provider:
    name: aws
    runtime: nodejs8.10

functions:
  web:
    handler: src/index.web
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true